background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.4
}

label {
    monitor =
    text = $TIME
    font_size = 48
    font_family = JetBrains Mono
    color = rgba(c0c4ccff)
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = $DATE
    font_size = 18
    font_family = JetBrains Mono
    color = rgba(c0c4cc99)
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 48
    position = 0, -60
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgba(5c909099)
    inner_color = rgba(14161aee)
    font_color = rgba(c0c4ccff)
    fade_on_empty = false
    placeholder_text = <i>touch key or enter password</i>
    dots_center = true
    shadow_passes = 2
}
